### ISSUE TITLE
Multiple Sec-Origin-Policy headers

### ISSUE THREAD

**Issue by dhausknecht** [mikewest/origin-policy#36] opened 2017-10-04 11:47 UTC
**Question:**
How do we handle multiple `Sec-Origin-Policy` headers in a response (or the same for `Sec-Origin-Manifest` in future)?

**Discussion:**
Spontaneously I would take the first valid header. But this should be defined somewhere.

(This question was asked by Lucas Garron on https://groups.google.com/a/chromium.org/d/msg/blink-dev/mdkHs4jybG4/EBOVwTifAQAJ)

**Comment by annevk** [comment] 2017-10-04 17:20
https://fetch.spec.whatwg.org/#should-response-to-request-be-blocked-due-to-nosniff? also does first. It's a bit of a hit-or-miss across browsers what various headers end up doing though, see also https://github.com/httpwg/http11bis/issues/32.

I suspect defining first is the best we can do or failing somehow if there's more than one.

**Comment by lgarron** [comment] 2017-10-06 01:01
[HSTS spec](https://tools.ietf.org/html/rfc6797#section-8.1):

> If a UA receives more than one STS header field in an HTTP response message over secure transport, then the UA MUST process only the first such header field.

[HSTS spec](https://tools.ietf.org/html/rfc7469#section-2.3.1):

> If a UA receives more than one PKP header field or more than one PKP- RO header field in an HTTP response message over secure transport, then the UA MUST process only the first PKP header field (if present) and only the first PKP-RO header field (if present).

I've sent https://github.com/WICG/origin-policy/pull/37, although I only attempted to update *client* processing.

**Comment by domenic** [comment] 2019-10-31 18:30
My understanding, confirmed with @annevk on IRC, is that the "correct" thing to do for newly-introduced headers is to treat multiple header lines the same as one header line with a comma in the middle. The primitive is https://fetch.spec.whatwg.org/#concept-header-list-get-decode-split .

Given the [latest header design](https://github.com/WICG/origin-policy/blob/master/version-negotiation.md), this would mean that e.g. you could do

```
Origin-Policy: allowed=(policyA polB polC none)
Origin-Policy: preferred=policyZ
```

which would be the same as

```
Origin-Policy: allowed=(policyA polB polC none), preferred=policyZ
```

For a case more like what I think is being asked here, consider

```
Origin-Policy: allowed=(policyA), preferred=policyB
Origin-Policy: allowed=(policyX), preferred=policyY
```

which per the above is isomorphic to

```
Origin-Policy: allowed=(policyA), preferred=policyB, allowed=(policyX), preferred=policyY
```

which [per the structured headers spec](https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html#rfc.section.4.2.2) (step 2.2) is a failure, and will cause the header to be discarded.

I guess what remains is to decide whether malformed `Origin-Policy` headers cause a network error, or are ignored.

**Comment by annevk** [comment] 2019-11-01 10:56
I'd prefer "brick my site if I made a typo" to be a separate opt-in and we should really only do that once there's a more concrete use case around that. E.g., I assume the way we process the JSON is going to be ignoring unknown / typo'd fields so it'd be weird to not be lenient here.

**Comment by domenic** [comment] 2019-11-04 21:29
I created a general issue for error handling in https://github.com/WICG/origin-policy/issues/49

**Comment by domenic** [comment] 2019-11-19 21:56
Closing since multi-header handling is well defined by HTTP + structured headers, and once the spec actually makes us of those, we'll be good to go.

**Closed as completed by domenic** 2019-11-19 21:56 UTC
